# Generated by Django 4.0.2 on 2022-03-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(related_name='post', to='posts.PostCategory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_subcategory',
            field=models.ManyToManyField(related_name='post', to='posts.PostSubcategory'),
        ),
    ]
