# Generated by Django 4.0.2 on 2022-03-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_post_category_alter_post_post_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(to='posts.PostCategory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_subcategory',
            field=models.ManyToManyField(to='posts.PostSubcategory'),
        ),
    ]
