# Generated by Django 4.0.2 on 2022-04-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_post_category_alter_post_post_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['created_at'], 'ordering': ['-created_at']},
        ),
    ]
