# Generated by Django 4.0.2 on 2022-03-27 08:56

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profileavatarimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileavatarimage',
            name='avatar_image_url',
            field=models.ImageField(default='default_user_avatar.jpg', upload_to=user.models.get_avatar_image_upload_to),
        ),
    ]
